### PR TITLE
6.0.8 pages

### PR DESCRIPTION
**Pull request by timothyshambra**
- #409 Update horizontal separator component page 
- #411 Update progress tracker component page 
- #415 Update progress bar component page 

Todo: Add progress tracker sample code

### CODE REVIEW

**Review by kkoryaka — CHANGES_REQUESTED** [review]
@timothyshambra those pages need to use consistent structure. You need to use tabs to show example and and source code. My bad for not communicating it clearly. Please use breadcrumbs page as your example.
Screen Shot 2022-10-07 at 2 56 43 PM

**Comment by timothyshambra** [comment]
> @timothyshambra those pages need to use consistent structure. You need to use tabs to show example and and source code. My bad for not communicating it clearly. Please use breadcrumbs page as your example. Screen Shot 2022-10-07 at 2 56 43 PM

Not a problem. Updated to match the breadcrumbs page!

**Comment by kkoryaka** [comment]
@timothyshambra could you add headings to horisontal separator examples section? Because showing two straight  hr is kind of confusing. Add h3 "Default separator" and h3  "Dotted separator", make it look similar to blockquote example.
Screen Shot 2022-10-10 at 9 32 44 AM

**Comment by kkoryaka** [comment]
@timothyshambra also please update side nav link

**Comment by timothyshambra** [comment]
@kkoryaka - I split the two examples into sections, and updated the sub nav.

**Comment by timothyshambra** [comment]
@kkoryaka ready for review

**Comment by timothyshambra** [comment]
@kkoryaka - ready for review!

**Review by kkoryaka — APPROVED** [review]

**Pull request merged**
